---
# tasks file for controller
- name: Install nginx.
  apt:
    name: nginx

- name: Configire nginx.
  template:
    src: templates/kubernetes.default.svc.cluster.local.j2
    dest: /etc/nginx/sites-available/kubernetes.default.svc.cluster.local

- name: Enable nginx virtualhost configuration
  file:
    src: /etc/nginx/sites-available/kubernetes.default.svc.cluster.local
    dest: /etc/nginx/sites-enabled/kubernetes.default.svc.cluster.local
    state: link
  notify: start nginx

- name: Force all notified.
  meta: flush_handlers
