---
- name: Local action for deploy the coredns cluster add-on.
  hosts: 127.0.0.1
  gather_facts: False
  tasks:
  - name: Deploy the coredns cluster add-on.
    shell: kubectl apply -f https://storage.googleapis.com/kubernetes-the-hard-way/coredns.yaml

