---
- name: Local action for create certs and configs
  hosts: 127.0.0.1
  gather_facts: False
  tasks:
  - name: Create certs and configs
    shell: ./gen_cert.sh && ./gen_cnf.sh
    args:
      chdir: /home/appuser/microservices-05/kubernetes/the_hard_way

