---
global:
  scrape_interval: '5s'

scrape_configs:

#  - job_name: 'blackbox'
#    metrics_path: /probe
#    params:
#      module: [http_2xx]
#    static_configs:
#      - targets:
#        - 'http://ui:9292'
#        - 'http://comment:9292'
#        - 'http://post:5000'
#    relabel_configs:
#      - source_labels: [__address__]
#        target_label: __param_target
#      - source_labels: [__param_target]
#        target_label: instance
#      - target_label: __address__
#        replacement: 127.0.0.1:9115

  - job_name: 'cloudprober'
    static_configs:
      - targets: 
        - 'cloudprober:9313'

  - job_name: 'mongo-exp'
    static_configs:
      - targets:
        - 'mongodb_exporter:9216'

  - job_name: 'node'
    static_configs:
      - targets:
        - 'node-exporter:9100'

  - job_name: 'prometheus'
    static_configs:
      - targets:
        - 'localhost:9090'

  - job_name: 'ui'
    static_configs:
      - targets:
        - 'ui:9292'

  - job_name: 'comment'
    static_configs:
      - targets:
        - 'comment:9292'

